#!/usr/bin/env python3
# encoding: utf-8
# author: huangwj
# mail: huangwjwork@gmail.com
# blog: http://blog.csdn.net/u010871982
# file: admin123113
# time: 2018/4/13 17:35

import re

mess = "you are a big and small kk"

re_com  = re.compile(r'(.*?a)')
re_group = re_com.search(mess)
# print(re_group.group(0))
re_match = re_com.match(mess)
# print(re_match.group(0))
print(re_com.findall(mess))